### ISSUE TITLE
Native Android App

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#1]
Research to Native Android App. Explain all other team members what advantages this has against other methods..

**Comment by Capscreen** [comment]
Grundlegend gibt es wohl drei Mapping-Librarys, die sich etabliert haben und aktiv genutzt werden:  
</br>

**Mapsforge**
  - Open-Source, offline Map Library für Android oder allgemein Java-basierte Anwendungen
  - kann sogar in kommerziellen Produkten verwendet werden
  - Rendering auf lokalem Gerät über eigene Render-Engine
  - eine weiterführende und flexible API auf der Grundlage von OSM
  - kompaktes Datei-Format für das Speichern von Karten
  - Multi-Touch, hohe Details, läuft ab Android 2.3.3
  - ermöglicht die grundlegende Funktionalität einer App auf der Grundlage von OSM mit sehr wenig Aufwand
  - wurde bereits in vielen renomierten [Apps](https://github.com/mapsforge/mapsforge/blob/master/docs/Mapsforge-Applications.md) genutzt
  - POI Integration über SQLite ist gegeben und eigene POI können über Drittanbieter eingebunden werden
  - Overlay-System (mit ggf. Abstrichen bei der Performance, wenn es um sehr viele Elemente geht)
  - [Beispiel-Ansicht](https://github.com/mapsforge/mapsforge/blob/master/README.md)
</br>

**OSMDroid**
- bietet Tools und unterschiedliche Views, die in Android integriert werden können
- nur zuvor geladenen Map-Tiles können offline auch genutzt werden (Caching-Möglichkeiten sind gegeben)
- Overlay-Support für die Integration von Icons, das Tracken der Position und dem Plotten von 2D-Grafiken (Minimap, Kompass…)
- ebenfalls Multi-Touch Support
- Über Addon kann unter anderem auch [Routing](https://github.com/MKergall/osmbonuspack/) genutzt werden
</br> 

**Mapbox SDK**
- Bietet sehr viele Möglichkeiten der Customization anhand von 2D oder 3D Visualisierungen
- im Vergleich zu den vorherigen Beispielen deutlich performanter
- gute Einbindung von Geocoding möglich
- auch Integration von Directions API (Google) würde unterstützt werden
- verschiedene Caching-Möglichkeiten
- Offline-Karten und Offline-Routing ist ebenfalls möglich
- ausführlich angeben, dass Mapbox verwendet wurde
- ggf. Problem mit Datenschutz, aufgrund von anonymisiertem Datenaustausch mit Anbieter
- ausführliche [Dokumentation](https://docs.mapbox.com/android/maps/overview/), mit [Beispielen](https://docs.mapbox.com/android/maps/examples/create-a-simple-map-view/)
