### ISSUE TITLE
Routing algorithm

### ISSUE THREAD

**Issue by RomanKrajewski** [LB31/HikingForNerds#10]
Implementierung in Dart (siehe [Algo Resesarch](https://github.com/LB31/HikingForNerds/issues/7#issuecomment-546051530))
Ausgabeformat frühzeitig festlegen -- Liste von Punkten zum Rendern
Testen in Berlin
Flutter location package evtl benutzen

**Comment by RomanKrajewski** [comment]
[feature/routing_algorithm](https://github.com/LB31/HikingForNerds/tree/feature/routing_algorithm)

**Comment by dephiloper** [comment]
@RomanKrajewski soll das reviewed werden? Kannst dann ja jemand assignen und es in "in review" schieben.

**Comment by dephiloper** [comment]
@RomanKrajewski please clean this

**Comment by RomanKrajewski** [comment]
done
