### ISSUE TITLE
Offline map functionality

### ISSUE THREAD

**Issue by Capscreen** [LB31/HikingForNerds#11]
- Kartendaten aus einem Bereich oder anhand einer Route entlang runterlasen
- Format ist noch fraglich (pngs oder optimal wäre MBTiles)
- pngs müssten vorgerendert werden, MBTiles on-the-fly gerendert werden
- brauchen wir einen Server, der die png Files zur Verfügung stellt oder gibt es eine Api, wo man die Daten von zb. Ganz Berlin runterladen kann?
- könnte man ggf. das Rendering der MBTiles Auf einen Server auslagern?
- brauchen wir die Karte, die wir runterladen in der gesamten Auflösung oder reichen Abstufungen?
- verwendeten Speicherplatz im Auge behalten

**Comment by dephiloper** [comment]
Fortschritt bei der Nutzung von Offline Karten mit Flutter und dem flutter_map plugin.
Zu finden auf feature/offline-map. Da viele Bilddaten notwendig sind wurde git-lfs verwendet, deshalb vorher mit git-lfs bilder pullen!

Vektor mbtiles von [openmaptiles](https://openmaptiles.com/downloads/europe/germany/berlin/) von Berlin wurden auf [tileserver gl](https://github.com/maptiler/tileserver-gl) gehostet. Anschließend wurde mittels [tile-generation](https://github.com/CMU-CREATE-Lab/tile-generation#generating-and-fetching-tiles) rasterized png tiles erzeugt, welche daraufhin in flutter eingebunden werden konnten. Vorteil an diesem Verfahren Bounding Box kann bei rasterizing angegeben werden.

Aber:
* es kann nicht ganz Berlin als png tiles gerendert werden, da zu viel Speicher notwendig (vorallem bei detaillierten Zoomstufen)
* tile-generator besitzt kann nur bis zoom stufe 14 was nicht nah genug ist
* dieses System bietet eine möglich zur Verwendung von Offline Daten, ist jedoch umständlich

Ggf. mehr mit flutter mapbox gl plugin und on the fly rendering von Vektor mbtiles möglich.

**Comment by dephiloper** [comment]
own/thirdparty server for serving mvt/pbf files:
https://github.com/tobrun/flutter-mapbox-gl/issues/83
https://docs.mapbox.com/mapbox-gl-js/example/third-party/

support for style api:
https://github.com/tobrun/flutter-mapbox-gl/issues/17

offline support - downloading tiles:
https://docs.mapbox.com/help/troubleshooting/mobile-offline/

awesome vector tiles github collection:
https://github.com/mapbox/awesome-vector-tiles

self hosting vector map tiles using mbtiles:
https://openmaptiles.com/server/#install
https://github.com/maptiler/tileserver-gl
https://gis.stackexchange.com/questions/125037/self-hosting-mapbox-vector-tiles

android traffic exception (possible that it is obsolete):
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

style editor other than mapbox:
https://github.com/maputnik/editor

pbf to mbtile or directories:
https://github.com/systemed/tilemaker

**Comment by LB31** [comment]
Mal hier ein bisschen herumgespielt. Ich komme auch nur bis Stufe 14. Eine Quelle für gute mbtiles habe ich noch nicht gefunden
https://github.com/johnpryan/flutter_map

Könnten wir uns Platz sparen ohne Farben? http://maps.stamen.com/#toner
Müsste man mal testen

https://github.com/alfanhui/mbtilesToPngs Konverter
