### ISSUE TITLE
exporting gpx or geojson a security exception

### ISSUE THREAD

**Issue by dephiloper** [LB31/HikingForNerds#110]
`E/DatabaseUtils(16437): java.lang.SecurityException: Permission Denial: reading de.esys.esysfluttershare.EsysFlutterShareFileProvider uri content://de.berlin.htw.hiking4nerds.fileprovider.github.com%2Forgs%2Fesysberlin%2Fesys-flutter-share/files/route.geojson from pid=13641, uid=1000 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils(16437): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:781)
E/DatabaseUtils(16437): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:645)
E/DatabaseUtils(16437): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
E/DatabaseUtils(16437): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:114)
E/DatabaseUtils(16437): 	at android.os.Binder.execTransactInternal(Binder.java:1032)
E/DatabaseUtils(16437): 	at android.os.Binder.execTransact(Binder.java:1005)`

**Comment by jakubprogramming** [comment]
please also look up if you can prevent opening our apps inside telegram etc. when the file is opened

**Comment by Capscreen** [comment]
[known issue](https://github.com/esysberlin/esys-flutter-share/issues/27)

- furthermore I noticed, that this exception is not thrown on android 9 devices

**Comment by dephiloper** [comment]
Since this error does not directly affect our app, I think it will be the best to just close it for now.
