### ISSUE TITLE
Crash: What is this?

### ISSUE THREAD

**Issue by jakubprogramming** [LB31/HikingForNerds#146]
uid=10243(u0_a243) Thread-8 identical 3 lines
E/flutter ( 3927): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '_asList' was called on null.
E/flutter ( 3927): Receiver: null
E/flutter ( 3927): Tried calling: _asList()
E/flutter ( 3927): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 3927): #1      AndroidMotionEvent._asList.<anonymous closure> (package:flutter/src/services/platform_views.dart:402:74)
E/flutter ( 3927): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
E/flutter ( 3927): #3      ListIterable.toList (dart:_internal/iterable.dart:221:19)
E/flutter ( 3927): #4      AndroidMotionEvent._asList (package:flutter/src/services/platform_views.dart:402:85)
E/flutter ( 3927): #5      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:608:15)
E/flutter ( 3927): #6      _MotionEventsDispatcher.dispatchPointerEvent (package:flutter/src/rendering/platform_view.dart:650:20)
E/flutter ( 3927): #7      _MotionEventsDispatcher.handlePointerEvent (package:flutter/src/rendering/platform_view.dart:578:5)
E/flutter ( 3927): #8      _PlatformViewGestureRecognizer.handleEvent (package:flutter/src/rendering/platform_view.dart:512:7)
E/flutter ( 3927): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 3927): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 3927): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 3927): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 3927): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 3927): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 3927): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 3927): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 3927): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 3927): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 3927): #19     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 3927): #20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 3927): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 3927): #22     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter ( 3927): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter ( 3927):

**Comment by dephiloper** [comment]
The only known reason this occurs is the three finger tab (see https://github.com/flutter/flutter/issues/29294). But you said that the error was just thrown randomly. My tipp would be to just add the before my me mentioned line in your local dart build:

https://github.com/flutter/flutter/issues/20517#issuecomment-546421226
