### ISSUE TITLE
Restructure for page routing

### ISSUE THREAD

**Issue by mayo-s** [LB31/HikingForNerds#15]
Restructure code for page routing.

**Comment by mayo-s** [comment]
Flutter application code was restructured.

main.dart is only to be used for page routing.
lib/pages will be stored in pages directory.
lib/services like calculations, map requests etc. will be stored in services directory.
images and other assets will be stored in assets directory.

**Comment by mayo-s** [comment]
@jakubprogramming 
please checkout and varify recent changes on develop branch.

i will merge with master and make a pull request afterwards.

**Comment by dephiloper** [comment]
is this still in todo or can be previewed @mayo-s ?
