### ISSUE TITLE
Use flutter mapbox-gl plugin

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#20]
Da Leaflet initial für die Kartenumsetzung verwendet wurde, sich aber aufgrund der geringeren Speicherkapazität und verbesserten Darstellung auf vector tiles für das mapbox-gl plugin entscheiden wurde, müssen die realisierten Funktionalitäten nun angepasst werden. 

Plugin: https://github.com/tobrun/flutter-mapbox-gl

**Comment by dephiloper** [comment]
TODO @jakubprogramming routen zeichnen mit Robin zusammen absprechen
