### ISSUE TITLE
Height chart for found routes

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#21]
Es soll eine Höhenmetergraph umgesetzt werden, der anhand der aktuellen Position in der Wanderroute den Verlauf der Höhenmeter anzeigt. Des Weiteren soll recherchiert werden zu Bodenbeschaffenheit.

![small](https://user-images.githubusercontent.com/19599410/69065876-b6c7cc80-0a20-11ea-950a-de0ee7a8f419.png)

**Comment by LB31** [comment]
Es ist leider gar nicht so trivial an die Daten zu kommen, wie gedacht.

- OSM bietet nur vereinzelt Höhendaten an
https://wiki.openstreetmap.org/wiki/Key:ele
- https://www.freemaptools.com/elevation-finder.htm hat solche Daten, jedoch ohne API
- https://open-elevation.com/ (von OSM vorgeschlagen) deren public API ist leider offline
könnte man selber hosten, Datenmengen sind jedoch sehr groß (20+GB)
- https://developers.google.com/maps/documentation/elevation/intro Google kann das, aber natürlich nicht kostenlos
- https://openrouteservice.org/ **funktioniert**. Umsonst sind jedoch nur 200 Höhen Requests pro Tag. Romans Test Route hat z.B. 739 Nodes
- https://www.jawg.io/docs/apidocs/elevation/ ist **vielversprechend**. 10k Höhenanfragen pro Monat sind umsonst. Man kann jedoch viele Nodes in einen Request stecken (soweit ich das verstehe, wird noch von mir getestet). Ergo 10k Routen pro Monat
**Update**: empirische Tests haben ergeben, dass etwa 150 Nodes in einen Request passen. Bei der aktuellen Test Route wären das 5 Requests → 2000 Routen pro Monat

**Comment by dephiloper** [comment]
* setup open elevation service / if this does not work use current service
* show diagram interactively, for dragging
* zoom?

**Comment by LB31** [comment]
Betrachtete Chart Lösungen:

https://github.com/imaNNeoFighT/fl_chart
- third party
- [Doku ](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md) ist ok

https://pub.dev/packages/flutter_sparkline
- ich sehe nicht, wie man zur Laufzeit die Daten ändern kann. Ist auch ein unbeantwortetes [Issue](https://github.com/xqwzts/flutter_sparkline/issues/21) im Repo
- wäre an sich nicht schlimm, wenn man das Widget neu zeichnen würde, nehme ich an

https://pub.dev/packages/charts_flutter
- offiziell von Google
- hat [alles](https://google.github.io/charts/flutter/gallery.html), was man brauchen könnte 
- den Einstieg finde ich als Flutter Noob noch etwas schwer
- Sobald ich deren Code + dependencies entschlüsselt habe, wird das wohl the way to go sein

**Comment by LB31** [comment]
Zusätzlicher Gedankengang zu https://www.jawg.io/docs/apidocs/elevation/
- In Romans Teststrecke hatten wir ~750 Nodes für etwa 5km
- sagen wir also alle ~7 Meter ein Update
- pro Query kann man 150 Nodes senden. Würde man es z.B. bei einem Query belassen wollen, in dem Beispiel, hätte man alle ~35 Meter ein Höhenupdate
- diskutierbar wäre, ob das nicht reicht

**Comment by dephiloper** [comment]
Setup von open-elevation notwendig.
Beschaffenheit über tags wie zum beispiel surface oder sac_scale (siehe @RomanKrajewski ) alternativ highway (Autobahn, Alphalt, Sand).
Chart realisiert in stepped Intervallen.

**Comment by LB31** [comment]
TODO 10.12.19:

- feed chart with routes by a method
- make chart intractable. Smooth and not only by clicking
- return event with information which point is selected

**Comment by dephiloper** [comment]
Add transparent background. make chart below chart line more opaque like in the image in the ticket description

**Comment by LB31** [comment]
TODO 18.12.19

- add descriptions for axes
- make descriptions and chart interaction optional over a parameter
- find out if it's possible to get the distance of specific nodes
