### ISSUE TITLE
Draw/update routes/points in Mapbox Plugin

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#22]
Offline data sideloading and drawing routes in iOS.

**Comment by dephiloper** [comment]
TODO @Capscreen what have you learned?

**Comment by dephiloper** [comment]
check out develop and draw route from leaflet in mapbox

**Comment by Capscreen** [comment]
- es gibt zwei Möglichkeiten, eine Route einzulegen.
- Möglichkeit eins: 
  - Über die _addLine()_-Funktion des der MapboxController-Klasse
  - dort können Koordinaten in Form einer GEOJSON angegeben werden und verschiedene Parameter genutzt werden, um die Route visuell anzupassen
- Möglichkeit zwei:
  - GEOJSON als source in der style.json angeben
  - anschließend dann einen Layer in selbiger Datei angeben
  - [an diesem Beispiel](http://uber.github.io/react-map-gl/#/Documentation/getting-started/adding-custom-data) kann sich dabei orientiert werden
