### ISSUE TITLE
Hosting own vector tile server

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#24]
Es soll mit den Laboringeneuren besprochen werden, ob ein Server für das hosten eigener Vectortiles uns zur Verfügung gestellt werden kann.

https://imi-bachelor.htw-berlin.de/studium/labore/hinweise/laboringenieure/
https://imi-bachelor.htw-berlin.de/studium/labore/hinweise/virtuelle-maschinen/

**Comment by dephiloper** [comment]
Mail an Herrn Warnke:

> Sehr geehrter Herr Warnke,
> 
> ich schreibe Ihnen aufgrund unseres IMI Projektes, bei welchem wir eine Anwendung mit Kartendaten von OSM entwickeln müssen. Der Projektverantwortliche ist dabei Prof. Lenz.
> Damit diese Kartendaten nicht von allen Nutzern, bei der Verwendung unserer Anwendung, komplett heruntergeladen werden müssen, möchten wir gern einen Tileserver zur Verfügung stellen, der die Nutzer mit den notwendigen Tiles dynamisch versorgt. Diesbezüglich wollte ich in Erfahrung bringen, ob die HTW uns für die Bearbeitung des Projektes einen Server bereitstellen könnte. Und falls dies möglich ist, welche hardwarespezifischen Konfigurationen dabei möglich sind.
> 
> Mit freundlichen Grüßen und vielen Dank für die Auskunft
>

**Comment by dephiloper** [comment]
A debian 9 server was provided with 2 cores, 4gb ram and 30gb hard drive. In the following the tileserver will be setup on the server. For security reasons a nginx webserver will be created in front of the tileserver-gl as suggested on the [tileserver page](https://tileserver.readthedocs.io/en/latest/deployment.html).
