### ISSUE TITLE
Algorithmus testen und verbessern

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#25]
- 'statt intersection zu ntersection eigene wegnotes realisieren'
- 'und wenn ich noch bock habe, retries'

**Comment by dephiloper** [comment]
wie ist der status hier? @RomanKrajewski

**Comment by dephiloper** [comment]
TODO @RomanKrajewski

**Comment by RomanKrajewski** [comment]
Was gemacht wurde:
Algorithmus getestet indem eine Testroute erzeugt und angezeigt wurde.
Methode zur gewichtung von Wegen implementiert
Straßen für Autos schlechter gewichtet als Wanderwege
erzeugte Routen feiner ausgeben
