### ISSUE TITLE
Convert pbf data to mbtiles

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#26]
Für die Benutzung von des mapbox gl flutter plugins ist es notwendig vector tiles auf einem Server zu hosten. Diese müssen dafür in das mbtiles Format konvertiert werden.

Besteht die Möglichkeit osm.pbf tiles in mbtiles umzuwandeln, könnten so Daten von geofabrik genutzt werden (https://download.geofabrik.de/europe/germany.html). Dadurch würde man ausschließlich auf frei verfügbaren Kartendaten aufbauen und wäre nicht von openmaptiles abhängig.

**Comment by NovalisTheMagician** [comment]
# Problem
Um offline Maps mit Vector-Tiles anzeigen zu können benötigen wir MBTiles Dateien. Diese Dateien sind im Kern nur SQLite Datenbanken, die Tile-Informationen speichern, in Raster oder Vector Format.

# Möglichkeiten
Um diese dateien zu generieren benötigt man zu aller erst eine GEO Datasource (http://download.geofabrik.de/europe/germany.html) im osm oder pbf Format (pbf ist hierbei ein Binäres Format). Zur Konvertierung wird noch ein Renderer benötigt, der mit einem Stylesheet die GEO daten in MBTiles oder Rasterbilder konvertiert. Dazu kann entweder ein Tileserver (https://github.com/maptiler/tileserver-gl), für das Online-Rendering, oder ein Program (https://tilemill-project.github.io/tilemill/), für das Offline-Rendering (wobei hier nicht auf dem mobilen Endgerät gemeint ist), verwendet werden. 

Die offline Variante hätte den Nachteil, dass man die Kartendaten nicht oder nur schwierig aktualisieren kann.

Es existiert allerdings auch noch eine Library für das Rendern/Generieren von MBTiles names Mapnik.
Man gibt der Library Quell Shapefiles (welche auch nur Vectordaten darstellen und man ebenfalls von http://download.geofabrik.de/europe/germany.html herunterladen kann), ein TileStylesheet und diese generiert dann ein brauchbares MBTile.

Der haken ist, dass diese Library nur in C++, python und Node verfügbar ist. Mein proposal wäre daher, dass wir eine anbindung an die Library (in flutter) schreiben, damit wir die möglichkeit haben Mapdaten auf dem Endgerät zu rendern und damit möglicherweise den Tileserver nicht mehr brauchen. Die Shapefiles können wir uns von der geofabrik fetchen.

**Comment by NovalisTheMagician** [comment]
link zur library: https://mapnik.org

**Comment by dephiloper** [comment]
can be closed!
