### ISSUE TITLE
Plan - Route Preferences: Create page with functionality

### ISSUE THREAD

**Issue by dephiloper** [LB31/HikingForNerds#28]
A flutter page needs to be created for the Route preferences page of the app flow.
See: https://github.com/LB31/HikingForNerds/wiki/App-flow#route-preferences
Communicate with @jakubprogramming to agree on a unified structure

The page gets an LatLng (or Node or 'RouteQuery') object as parameter from the Location Specification page and gathers additional information like route length (distance in kilometers), list of poi categories (searchbar) and the altitude difference of a route.

**route length**
For this setting a conversion service needs to be implemented between route length in kilometer and in minutes (while using a specified step length). The option should be toggable (between time and distance). The slider should have the option to set a min and max value.

**poi categories**
Perhaps a service could be implemented aswell but is not completelly necessary imo. For a list of possible poi's @RomanKrajewski recommended the following lists:
https://taginfo.openstreetmap.org/keys/tourism#values
https://taginfo.openstreetmap.org/keys/amenity#values
From both sites only keys with a high count and a discription should be used (manually written into the list or read into the application from a text file).

**altitude difference**
This option could be implemented with three toggable buttons where only one is enabled.

The gathered informations should be passed to the next page (Plan - Route Selection).

**Comment by mayo-s** [comment]
Route distance: Slider, InputField
Categories/Characteristics: Chips, ToggleButton, RadioButton, Menu (MultipleChoice) (, Search field?)

**Comment by mayo-s** [comment]
Get Map Key Values, Create search field. If Key selected add chip.
Finally hand over distance and key values to algorithm

**Comment by mayo-s** [comment]
example queries:

search for keyword (keywords that are are somehow connected to the query value): https://taginfo.openstreetmap.org/api/4/search/by_keyword?query=church&page=1&rp=10

search by value (whatever has the value in its name):
https://taginfo.openstreetmap.org/api/4/search/by_value?query=church&page=1&rp=10

search for keys with tag value (i.e. a "church" is a building)
https://taginfo.openstreetmap.org/api/4/projects/tags?sortname=projects&sortorder=desc&page=1&rp=100&query=church

**Comment by mayo-s** [comment]
last commit added chips and a static search list.
Future version is supposed to have multiple chips and a service requesting possible keys for user input.
Therefore I need to do a few more changes on the search widget I am using and fetch as well as parse data from osm api.
<img width="334" alt="Screenshot 2019-12-02 at 19 32 11" src="https://user-images.githubusercontent.com/15143379/69985218-0e932700-153b-11ea-8adf-feefdf4b7ea1.png">
check it out on feature/routesetuppage

**Comment by mayo-s** [comment]
Add required functionality with last commit (feature/routepref).
Segement_Navigation needs to be double checked an adapted.
'GO'-Button can send whatever params holds, but does not yet have a Function (only print to double check values)

<img width="150" alt="Screenshot 2020-01-04 at 22 24 00" src="https://user-images.githubusercontent.com/15143379/71772042-8c848c80-2f44-11ea-8aca-f5c1167b011e.png">
