### ISSUE TITLE
Create a bottom bar to navigate between app segments

### ISSUE THREAD

**Issue by dephiloper** [LB31/HikingForNerds#29]
Currently there is an implementation of an floating action button which expands when pressed to navigate between different pages. This should be changed into an bottom bar. The bottom bar should provide the following options:
* plan
* route
* settings

The bottom bar should be avaiable on all pages so it should be set globally if possible.
An example can be viewed here: [link](https://i.ytimg.com/vi/8YsO1FOLy5s/maxresdefault.jpg) and [link](https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F0B6xUSjjSulxcczRPSWxidHVCSjQ%2Fbottomnav-color-do-2.png)

**Important** the button bar should be avaiable with action button and without.

**Comment by dephiloper** [comment]
@mayo-s I provided the description we discussed in a previous week, here. Please complete it further.

**Comment by mayo-s** [comment]
Navigation as seen in App flow is now a component (branch _feature/redesign_bottombar_).
Current problem is the navigation within the Stack of pages. I'd like to avoid duplicate entries when again clicked but already on the stack or even same page.
Might take a moment. I am on it.
<img width="301" alt="Screenshot 2019-12-12 at 16 02 13" src="https://user-images.githubusercontent.com/15143379/70723241-dfc63f00-1cf8-11ea-9b23-50ab5355ae1d.png">

**Comment by dephiloper** [comment]
looks promising!

> I'd like to avoid duplicate entries when again clicked but already on the stack or even same page.

I think also it is neccessary to aim for this behavior, otherwise the user would have for example two different states inside the plan section. For now I think it is okay if this does not work perfectly and we discuss the navigation behavior later or you come up with a nice solution.
