### ISSUE TITLE
Share route with others

### ISSUE THREAD

**Issue by dephiloper** [LB31/HikingForNerds#31]
Make up a nice way to share your route with others.
* starting point
* seed
* length
or
* complete route?

**Comment by Capscreen** [comment]
- "gpx" package for GPX
- "Geojson" package for automatic generation of a Geojson-file containing LatLng-points
- Seed discarded for now, because the calculation of a route could be inefficient at the moment

**Comment by jakubprogramming** [comment]
A function for converting the "route file" back to its original format, so that it can be drawn onto the map (by me) again would also be fantastic!

**Comment by Capscreen** [comment]
This would be necessary with the upcoming import feature anyway. So your idea definitely has to be implemented in the future.

**Comment by dephiloper** [comment]
@Capscreen create issue for _import shared route_
