### ISSUE TITLE
Fine tune route generation

### ISSUE THREAD

**Issue by dephiloper** [LB31/HikingForNerds#33]
* implement alternative routes
* point of interests
* set weights for way, how to use tags for ways

**Comment by RomanKrajewski** [comment]
alternative routes: done
set weights for way: done
also improved distance function so that the length of a route can be calculated more accurately

pois not done yet, started to implement a function that returns a route that includes a node with a chosen [tourism tag](https://wiki.openstreetmap.org/wiki/Key:tourism) value

**Comment by dephiloper** [comment]
add a single point of interest to the currently calculated route

**Comment by RomanKrajewski** [comment]
#### Möglicher POI Algorithmus ####
(sorry für deutsch, hatte ne idee und die muss möglichst schnell zu papier gebracht werden bevor ich sie wieder vergesse)
1. Menge aller passenden POI im radius ermitteln (OSM abfrage)
2. Einen random raussuchen, Distanz zu diesem ermitteln
3. Im Uhrzeigersinn von diesem den nächsten POI suchen, Distanz zu diesem ermitteln
     Schritt 3 wiederholen bis Distanz oder POI aufgebraucht oder 360 grad abgearbeitet
4. Wenn POI aufgebraucht, Distanz noch durch willkürlichen Umweg erweitern

**Comment by RomanKrajewski** [comment]
Implementiert wurde die suche nach einer route, welche von poi zu poi führt, wobei immer der nach luftlinie nächste POI genommen wird. Es fehlt noch die Verlängerung der Route wenn es zu wenig POI gibt um die gewünschte Streckenlänge zu erreichen. Dazu benötige ich eine Formel um ein Dreieck mit einem gegebenen Winkel, einer gegebenen Seite und gegebenem Umfang zu berechnen. Stehe da gerade auf dem Schlauch. Ebenfalls können mit diesem Algorithmus noch keine Alternativrouten berechnet werden.

**Comment by RomanKrajewski** [comment]
Ok, hab mich jetzt doch für die primitive Variante entschieden und die Routenverlängerung geht damit. Aber mit der oben genannten Formel könnten ungefähr ein drittel an OSM daten und ram gespart werden, also lohnt sich das immer noch herauszufinden.
