### ISSUE TITLE
Plan - Location Selection: Set Starting Point for Route Calculation on Map by Marker, Current Location or Address 

### ISSUE THREAD

**Issue by jakubprogramming** [LB31/HikingForNerds#37]
Implement different ways to set a starting location for the calculation of the route. 
Currently only the GPS device location is used. Instead also a marker or an address should be possible options.

https://github.com/LB31/HikingForNerds/wiki/App-flow#location-specification

**Comment by dephiloper** [comment]
@jakubprogramming TODO description please

**Comment by dephiloper** [comment]
![landing-page](https://user-images.githubusercontent.com/19599410/70145136-b295e300-169f-11ea-8c39-c610ef291b90.jpg)

**Comment by dephiloper** [comment]
* marker is centered on the screen
* location sets center of screen over current location (and thus also the marker)
* entered location in search bar resolves lat long and centers map there
