### ISSUE TITLE
Progressive Web Apps

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#4]
Research to Progressive Web apps, how they work, how to use them and if they are suitable for the project give an introduction for all other team members.

**Comment by NovalisTheMagician** [comment]
# tl;dr
Progressive Web Apps (PWA) sind gewöhnliche Websites, die drei zusätzliche Kern-elemente beinhalten müssen:
- sie müssen über eine TLS verbindung kommen (z.B. über HTTPS)
- es muss eine manifest.json datei vorhanden sein in der Metadaten über die PWA enthalten sind
- es muss mindestens ein Service Worker sein

Im großen und ganzen würde ich PWAs nicht für dieses Projekt empfehlen, da zu viele Abhängigkeiten enstehen (besonders wegen dem Server) und dadurch das Testen sehr nervig wird.

# PWA
Da PWA normale websites sind, kann man auch alle bestehenden Webtechnologien und libraries verwenden.
PWA haben auch die möglichkeit offline Verfügbar zu sein, allerdings muss man dafür die Service Worker verwenden. Service Worker sind im grunde normale WebWorker (WebWorker sind die Threads fürs web, aber nicht komplett...). Die Service Worker haben die möglichkeiten Push Benachrichtigungen an den Benutzer zu senden und um Daten im voraus zu fetchen für den Offline-modus.

## Vor-/Nachteile im bezug auf das Projekt
### Positiv
- Gewöhnliche Webapps, welche man responsive designen kann (Mobil und Desktop Platform agnostisch)
  - kann fast jede beliebige Bibliothek verwenden
  - kann alle Sensoren verwenden auf die der Browser zugriff hat (GPS)
- offline Verfügbar für die Waldnavigation
- _einfach_ Aktualisierbar und Installierbar
### Negativ
- umständliche Infrastruktur (benöntigt HTTPS Server)
  - nervig zu Testen, da server benötigt wird
- Cachesize ist limitiert
  - je nachdem wie groß die Kartendaten werden könnte der Offline-modus entfallen

**Comment by NovalisTheMagician** [comment]
# Update
Anscheinend ist der Cachestorage limit nicht eindeutig definiert und hat daraus zu folge, dass einige Browserhersteller ein Zeitlimit setzen auf die Cachedaten. (z.B. Apple setzt ein limit von 2 Wochen).

Man könnte dies umgehen, wenn man die localStorage oder IndexedDB APIs verwended, welche auch ein größeres  speicher limit haben.
