### ISSUE TITLE
OpenStreetMap API

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#5]
How to use the openstreetmap api to query map information, filter data and get information about streets and points.

**Comment by RomanKrajewski** [comment]
### OSM API Research Bericht ###
#### Lesen von Kartendaten ####
Rohe Kartendaten kann man mithilfe von der Overpass API lesen. Diese wird mithilfe einer eigenen Query language angesprochen. Damit kann man beispielsweise innerhalb einer BoundingBox nach Nodes mit bestimmten Tags suchen und diese als JSON zurückerhalten.
[Overpass Query Language](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Language_overview)
Diese API ist sehr mächtig und wir werden damit wahrscheinlich alle Informationen über unser Zielgebiet finden, die wir suchen. Automatische Routenfindung unterstützt diese API allerdings nicht.

#### Finden von Routen ####
Falls wir uns die Routenfindung ganz einfach machen wollen, können wir GraphHopper verwenden. Das ist eine  Web API zur Routenberechnung, mit der man sogar einen Rundweg mit Wunschlänge finden lassen kann 😄 
[GraphHopper Routing Query](https://docs.graphhopper.com/#operation/getRoute/parameters/algorithm)
Mit GraphHopper lassen sich allerdings auch Distanzmatrizen für eine Menge an Zwischenzielen berechnen, was für eine RoutenFindung anhand von Points of Interests praktisch wäre.
Das geht auch mit [Open Route Service](https://openrouteservice.org/), einer anderen Web API die ebenfalls Routenfindung anbietet.

Wenn wir auf das alles verzichten wollen können wir natürlich auch einen eigenen Algorithmus zur Routenfindung mittels der Rohen OSM Daten schreiben. Ob es Sinnvoll ist, dafür eine Library wie zb [Google OR Tools](https://developers.google.com/optimization) zu benutzen ist fraglich, da diese meistens nach der kürzesten Route, anstatt einer Route mit bestimmter Länge, suchen. Aber vielleicht könnte man da mal in den GraphHopper Source Code gucken, wie die das machen.

**Comment by dephiloper** [comment]
### OSM API Research Bericht (die Zweite)

#### Preamble
Da sich Roman bereits mit den verschiedenen APIs auseinandergesetzt hat, die wir nutzen können um OSM Daten zu erhalten, habe ich versucht diese zu benutzen bzw. Beispiele damit zu erzeugen, um dazu Informationen zu liefern. Des Weiteren habe ich zwecks Rendering der Kartendaten recherchiert. Ggf. stellt sich jedoch heraus, dass keine explizite Rendering Library notwendig ist, da diese bereits von dem genutzten Mobile Framework von Haus oder als 3rd party lib mitgeliefert wird.

#### Overpass API
Um Overpass testweise zu nutzen existiert die Seite [Overpass Turbo](https://overpass-turbo.eu/). Damit lassen sich auf einer Website Query-Requests an die API schicken und, durch die Einbindung einer dynamischen Karte, ebenfalls betrachten.
Die Overpass QL definiert die drei möglichen Typen von Objekten, die durch eine Anfrage an die API zurückgeliefert werden können:
* *node* (gebe alle Punkte für die angegebene Suchanfrage zurück)
* *way* (gebe alle Wege .., wobei Wege sowohl innerhalb eines Bereichs als auch Wege die diesen Bereich verlassen gefunden werden)
* *relation* (findet Punkte oder Wege mit einer bestimmen Rolle in Relation)
  * [Beispiel](https://overpass-turbo.eu/?Q=rel%28%7B%7Bbbox%7D%7D%29-%3E.relations%3B%0A%0A%28+%0A++node%28r.relations%3A%22via%22%29%3B%0A++way%28r.relations%3A%22via%22%29%3B%3E%3B%0A%29%3Bout%3B): ermittle alle Punkte und Wege mit der Rolle 'via'

Wie bereits von Roman mitgeteilt kann meine eine Bounding Box durch die Angabe von lowest latitude (southernmost), lowest longitude (westernmost), highest latitude (northernmost), highest longitude (easternmost) angeben und auswerten. Zusätzlich gibt es die Möglichkeit innerhalb der spezifizierten Bounding Box Filter anzuwenden. Mittels des *amenity* Filters können bestimmte POI angezeigt werden.
* [Auflistung von *amenity keys*](https://wiki.openstreetmap.org/wiki/Key:amenity)
* interessante [Auflistung](https://taginfo.openstreetmap.org/keys/amenity#values) der Prozentwerte an verteilten Tags

*Public Overpass API instances Any of the three servers has a total capacity of about 1,000,000 requests per day. You can safely assume that you don't disturb other users when you do less than 10,000 queries per day and download less than 5 GB data per day.*

#### GraphHopper Routing Query
Da GraphHopper kostenpflichtig ist, bin ich mir nicht sicher ob hier eine tiefere Recherche notwendig ist (siehe [Pricing](https://www.graphhopper.com/pricing/)).
Ein Request kostet 1 Credit, wobei man in der Free Version 500 Requests frei hat, was sogar schon beim Testen zu Problemen führen könnte. GraphHopper ist aber eine sehr umfangreiche API, welche eine Vielzahl von Services bietet und ebenfalls [Integrationen](https://docs.graphhopper.com/#section/Explore-our-APIs/API-Client-Libraries) für gewisse Sprachen mitbringt. 

#### Open Route Service
Bietet kostenlos 2500 Requests pro Tag an. Ist eine Rest-Api mit Abfragen zu:
* Directions (Routen mit n Zwischenpunkten) 
* Isochrones (ermittelt Gebiete der Erreichbarkeit, ausgehend von einer Location)
* Matrix (1-1, 1-n, n-m Matrizen für Zeiten und Distanzen)
* Geocode (Koordinaten zu Adressen auflösen und andersherum)
* Pois (Points of interest)
* und weitere

Mit ORS könnte man Punkte definieren und zwischen diesen Punkten anschließend mit der Directions API (https://api.openrouteservice.org/v2/directions/api_key=your-api-key&start=8.681495,49.41461&end=8.687872,49.420318) den shortest path ermitteln.
Anschließend alle Punkte Wege verbinden oder ggf. eine Route mit multiplen Punkten wählen.

Benutzung der Python Api um gesperrte Straßen in Berlin für Dieselfahrzeuge zu umgehen: [Jupyter](https://openrouteservice.org/dieselgate-avoid-berlin-banned-diesel-streets/)

### Rendering
[Tangram ES](https://github.com/tangrams/tangram-es) ist eine Library um Kartendaten auf mobilen Endgeräten in 2D und 3D zu rendern, welche mittels OpenGL ES implementiert wurde. Diese Library sieht echt vielversprechend aus, ist prinzipiell eine Mobile Abwandlung der WebGL Version Tangram und ist visuell, wenn man laut der [Demo](https://github.com/tangrams/simple-demo) urteilt, individuell anpassbar (+ gute Doku).

Eine andere Anlaufstelle wäre die [Carto SDK](https://carto.com/developers/mobile-sdk/), welche ebenfalls [sehr gut dokumentiert](https://carto.com/developers/mobile-sdk/) ist und eine Mobile Einbindung besitzt.

Zusätzlich existieren noch [Leaflet](https://leafletjs.com/), welche ja fast schon der Standard geworden ist, wobei ich sagen muss, dass mich das visuell nicht von den Socken haut und [Mapbox](https://www.mapbox.com/pricing/), welches eher für den Businessbereich ist, sehr umfangreich entwickelt, extrem gut dokumentiert, aber nur bis 25.000 Nutzer kostenlos, somit eher nicht geeignet ist.

Weitere Libraries dazu können [hier](https://wiki.openstreetmap.org/wiki/Frameworks#Webmaps) gefunden werden. Wichtig zu erwähnen ist, dass nicht jede Library zusätzliche Navigation und Location Funktionalitäten besitzt. Diese müssen dann ggf. selbst realisiert werden.

**Comment by RomanKrajewski** [comment]
### Beispielqueries ###
Um ein bisschen in die Query Language einzusteigen und euch den Einstieg etwas zu erleichtern habe ich mal zwei Beispielqueries mit Kommentaren erstellt, die Wanderrelevante Daten auslesen.
Fragen dazu beantworte ich gerne am Mittwoch, kann sie auch vorstellen, falls Interesse daran besteht.

[Finde eine Node mit Namen und alle Wanderwege um Umkreis von 1km](https://overpass-turbo.eu/s/NjR)

[Finde alle Wanderwege auf dem aktuell angezeigten Kartenabschnitt](https://overpass-turbo.eu/s/NjU)

**Comment by RomanKrajewski** [comment]
> Da GraphHopper kostenpflichtig ist, bin ich mir nicht sicher ob hier eine tiefere Recherche notwendig ist (siehe Pricing).
> Ein Request kostet 1 Credit, wobei man in der Free Version 500 Requests frei hat, was sogar schon beim Testen zu Problemen führen könnte. GraphHopper ist aber eine sehr umfangreiche API, welche eine Vielzahl von Services bietet und ebenfalls Integrationen für gewisse Sprachen mitbringt.

Wenn ich die [GitHub Page](https://github.com/graphhopper/graphhopper) richtig verstehe, kann man GraphHopper auch als Maven Dependency in Android Projekte einbauen. Das sollten wir auf jeden Fall im Hinterkopf behalten.

**Comment by dephiloper** [comment]
Weiterführende Recherche [issue-7](https://github.com/LB31/HikingForNerds/issues/7).
