### ISSUE TITLE
Find a good route with multiple POIs

### ISSUE THREAD

**Issue by RomanKrajewski** [LB31/HikingForNerds#58]
I just did some research regarding the algorithms needed to find a good route that includes POIs chosen by the user.

To find a route that is not longer than 1.5 times the optimal round given a set of POIs two algorithms need to be implemented:

1. [Kruskal's Algorithm](https://en.wikipedia.org/wiki/Kruskal%27s_algorithm) to find a minimum Spanning tree
2. [Christofides algorithm](https://en.wikipedia.org/wiki/Christofides_algorithm) to solve the Traveling Salesman Problem with that minimum Spanning tree

To implement these two algorithms is quite a bit of work so i want to make sure the requirements to the route generation algorithm for routes including POIs are set and i understood them correctly.

In my understanding the user scenario we agreed to on wednesday would be something like the following:

1. The user chooses a set of unordered POIs and no expected route length
2. The algorithm returns the approximately shortest possible route with those POIs

In my opinion it could be difficult to include this in the user interface in a consistant manner and as a user I might ask myself: why can't I specify a route length when trying to include POIs in the route. For this reason I want to make the case for the algorithm that is implemented already, just to make sure we really want to change it.
[what is implemented right now](https://github.com/LB31/HikingForNerds/issues/33#issuecomment-561409100)
Advantages: 

- User can specify a route length
- POIs are chosen automatically by specifying a category

Disadvantage:

- Order of POIs might be suboptimal, but that doesn't really matter since a route with the specified length is expected, not the shortest

A compromise between the two solutions would be that the user chooses the POIs and gives an expected route length, and a route with these parameters gets generated, using the nearest neighbor approach.

I'm looking forward to your feedback and apologize for the long issue. Implementing these algorithms just felt like its not really what we want and a bit too time consuming to just do it when we're not sure we want it.

**Comment by Capscreen** [comment]
I think the user should get the opportunity to choose a sequence of POIs **and** a _minimum_ distance of the calculated route (I mean, he/she wants to hike right?). This would mean, the route could be longer anyways and it would look legit to the user that an increasing number of POIs would lead to an increasing length of his route.

**Comment by RomanKrajewski** [comment]
The minimum route length parameter is a good idea imo. But for that the Traveling Salesmen Problem doesn't need to be solved either.. The only case in which it matters is when the user wants to hike the minimal required distance to reach the given POIs. And since we wouldn't solve that case optimally anyways I'm not sure whether the algorithms are really necessary or the nearest neighbor approach would be close enough already.

**Comment by dephiloper** [comment]
During our conversation last Wednesday, we decided on the following core functionalities for the time being:
* determining a random route after specifying a fixed length
* **determine a route with point of interests you select before**

The first functionality is already implemented like that.
The second point could be understand in two different ways:
1. user specifies what kind of poi's he is interested in (categories) and a route will be generated with those kind of pois
(e.g. interested in viewing platforms and hiking huts -> random route with viewing platform/s and/or hiking hut/s)

**or**

2. user specifies what kind of pois he is interested in and all those possible poi's in his range are now listed (with distance and sorted to the user) for him to select. After selecting an maximum amount of _n_ poi's an random route will be generated with those routes, but an max length would not be required here

**Comment by dephiloper** [comment]
Personally I would prefer the second approch because it is much more interesing to see what kind of pois are nearby and to choose myself which of them should be included in my route.
But I see other people that are not so much interested in this point and just want to walk a nice route and see interesting stuff (from categories they specified) on their way.

Would it be possible to create all three behaviors?
1. random route
2. random route with poi categories
3. route with specified pois

What part would be the most time consuming?

UX-wise how to explain those three types of route search is hard indeed. Eventually we discuss this in the next meeting tuesday.

**Comment by mayo-s** [comment]
On my hand side I'd prefer a specified route length and if it happens to have certain POIs - nice to have but for me not mandatory. But I can also see that this kind of selection can be confusing to users. Therefore at least a "warning" like "route caluclation might take a minute or two" should be displayed and agreed to. I like Philips 3 cases of behavior and would UI sided blank out or disable non available options, always accompanied a a little explanary side note. Nothing fancy, but easy to understand.

**Comment by RomanKrajewski** [comment]
> Would it be possible to create all three behaviors?
> 
>     1. random route
> 
>     2. random route with poi categories
> 
>     3. route with specified pois
> 
> 
> What part would be the most time consuming?

I agree that we should implement these three scenarios. The time consuming part is to calculate an optimal route between the POIs, so we have to decide if thats worth it. We can implement all these three things without calculating an optimal route.  

> After selecting an maximum amount of n poi's an random route will be generated with those routes, but an max length would not be required here

What do you mean with max length? I think the behavior robin described, where a minimum route length is shown to the user and he can make it longer if he wants to, would be the easiest to include the consistently, since the length parameter is still there, just restricted by the number of POIs. 

I would propose we implement these 3 scenarios with the nearest neighbor approach and see how that goes, if the results are too bad we can try the algorithms I described above.

**Comment by dephiloper** [comment]
> What do you mean with max length?

I meant a length in itself. We discussed that, if the user wants to specify pois himself he must dispense with the specification of a route length.

> think the behavior robin described, where a minimum route length is shown to the user and he can make it longer if he wants to, would be the easiest to include the consistently, since the length parameter is still there, just restricted by the number of POIs.

IMO we can go with the minimum route length on all three approaches and on scenario 3 the calculated routes start at an different minimum route length as stated from you, if you ment that by restricted.

I would also like to discuss the user handling of the routing process, because there are different specifications on scenario 1 and 2 in contrast to 3.
