### ISSUE TITLE
Route Object

### ISSUE THREAD

**Issue by RomanKrajewski** [LB31/HikingForNerds#60]
Route Objects with the following fields:

- List of Nodes representing the Path
- Total route length
- Höheninformationen
- Höhenmeter Gesamtzahl
- List of POI representing the POIs
   - POI: erbt von Node, plus Map of Keys and Tags

**Comment by Capscreen** [comment]
- TODO from issue #31 needs to be updated for Route Object
- notify me or change by yourself

**Comment by RomanKrajewski** [comment]
@LB31 Can you add height information to the route object?

**Comment by LB31** [comment]
@RomanKrajewski I will. My suggestion is that the route constructor is responsible for actually querying them.
