### ISSUE TITLE
Create Settings Page

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#65]
https://github.com/LB31/HikingForNerds/wiki/App-flow#settings

**Comment by LB31** [comment]
<img src="https://user-images.githubusercontent.com/15799249/71607980-f59f8500-2b7d-11ea-82f6-28d6272faac1.jpg" width="40%" height="40%">

I added some kinds of interaction dummies. Now we need to define what can be set in the settings

**Comment by LB31** [comment]
Possible settings:
- Save History (boolean)
- Use location (boolean)
- Units (km or miles..)
- Delete downloaded maps (show current amount and size on device)
- Maximum route length
- Maximum route elevation
- ...

**Comment by Capscreen** [comment]
- delete history
- language

**Comment by LB31** [comment]
| <img src="https://user-images.githubusercontent.com/15799249/71946382-ef3a8a00-31c9-11ea-852b-5675cc92f354.jpg" width="40%" height="40%">  | <img src="https://user-images.githubusercontent.com/15799249/71946706-e4ccc000-31ca-11ea-80e5-47424728494e.jpg" width="40%" height="40%"> |



Current state. The elements are persistent.

TODO:
- Create Signleton getter/setter class for the values
- Adjust the layout
- remove the examples at the bottom
