### ISSUE TITLE
Algorithmus

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#7]
Welche Daten bekommt man von OSM?
Welche Algorithmen gibt es?
Welche Datenstrukturen brauchen diese Algorithmen?

**Comment by RomanKrajewski** [comment]
### Algorithmus Research ###
#### Funktionsweise Graphhopper ####
Um herauszufinden, welchen Algorithmus wir benutzen, habe ich mir [GraphHopper](https://github.com/graphhopper/graphhopper) mal genauer angeguckt. Diese Library ist auf Server und damit auf das Lösen von möglichst vielen Routing Problemen in möglichst kurzer Zeit ausgelegt. Damit einher geht allerdings ein hoher Speicherbedarf und relativ langes Preprocessing der OSM Daten. Dabei werden ganze .pbf Files vorverarbeitet und damit schnelles Routing für eine große Region ermöglicht.

Ich würde vorschlagen wir versuchen eine schlankere Version davon zu bauen, indem wir mittels Overpass Queries die Datenmenge von vornherein gering halten (wir brauchen eh nur die bewanderbaren Wege eines relativ kleinen Gebiets). Damit müssten wir zwar für jede Routenberechnung das Preprocessing durchführen, würden dieses aber möglichst klein halten. Dadurch hätten wir langsamere Queries, aber bedeutend weniger Speicherbedarf.

Hier die [Grundlegende Funktionsweise von GraphHopper](https://github.com/graphhopper/graphhopper/blob/0.13/docs/core/technical.md). Überraschenderweise wird als Datenstruktur ein Graph verwendet.

#### Algorithmus für Rundweg ####
Der Algorithmus funktioniert bei GraphHopper folgendermaßen:
1. Generieren eines regelmäßigen Polygons mit Umfang = gewünschte Rundweglänge und Startpunkt als Eckpunkt
2. Finden der nächsten Nodes im Graphen zu Eckpunkten des Polygons
3. Finden von Routen mittels bidirektionalem A* Algorithmus von Node zu Node. Dabei werden die weights vom Graphen nach jeder Route zwischen einem Nodepaar angepasst, sodass bereits besuchte Wege vermieden werden. (Sonst könnte es passieren, dass auf der Route von B zu C Wege benutzt werden, die schon von A zu B benutzt wurden, was zu einer Wanderroute führen würde, bei der man bestimmte Strecken hin und direkt wieder zurück laufen würde)
(siehe [RoundTripRoutingTemplate](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/routing/template/RoundTripRoutingTemplate.java)).

**Comment by LB31** [comment]
Nebst Graphhopper gibt es andere ähnliches Services 
https://wiki.openstreetmap.org/wiki/Routing#Developers

### Openrouteservice
https://github.com/GIScience/openrouteservice

- free Plan ist ganz ok. 2000 direction, 5000 poi requests... am Tag
- Sign up for API funktioniert bei mir grad in keinem Browser https://openrouteservice.org/plans/
- bieten bereits Routenberechnungen zum Wandern an https://maps.openrouteservice.org/
- Rundweg lässt sich in der Demo zusammenklicken
- Nachteil: man ist vom Internet abhängig

### OsmAnd
https://wiki.openstreetmap.org/wiki/OsmAnd

- funktioniert offline
- mit iOS und Android
- ist an sich eine fertige Anwendung. Wir können uns höchstens im Code umgucken
https://github.com/osmandapp/Osmand
- Machen wir vermutlich eh nicht. Nevermind


### Meine Meinung
- Mit Graphhopper fahren wir vermutlich ganz gut
- Es wäre super, wenn wir einen Service verwenden würden, der uns vieles abnimmt
- Klar können wir auch selbst einen A*... implementieren und mit OSMs API rumspielen
- Mit einem entsprechenden Tool hätten wir jedoch mehr Zeit für andere Features 
- muss morgen leider früh raus. Die Recherche oben setze ich jedoch fort. Vllt findet sich ja noch etwas Gutes
