### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#8]
- Sich reinarbeiten
- Leaflet Anbindung inklusive Plugins angucken

**Comment by NovalisTheMagician** [comment]
# Flutter + VSCode (on Windows):
Flutter selbst ist nur eine Collection von Libraries und build-tools um cross-platform Apps zu entwickeln. Dies bedeutet, dass man 'theoretisch' jeden beliebigen Editor verwenden kann. Auf der flutter website sind allerdings nur anweisungen für zwei beliebte IDEs vorhanden: Android Studio und Visual Studio Code. 
Allerdings ist das auch nicht zu 100% wahr. Wenn man der Anleitung für VSCode geht, dann muss mann an einem Punkt dennoch Android Studio installieren, um an die Android SDK heran zu kommen.
Es gibt jedoch einen umweg: man lädt sich die command line tools (https://developer.android.com/studio#downloads) herunter und installiert alle anderen benötigten sdks mithilfe der sdkmanager.bat script datei herunter

Wer eine GUI variante für das downloaden der benötigten sdks verwenden will muss sich zusätzlich noch dieses tool downloaden (https://www.b4x.com/android/forum/threads/gui-sdk-manager-for-newer-versions-of-android-tools.80090/)

Zum schluss muss noch eine Environment Variable in Windows gesetzt werden die ANDROID_HOME heißt und zum root des android sdk ordners zeigt.

In VSCode muss letztendlich noch das flutter plugin installiert werden und man ist bereit flutter apps mit VSCode zu entwickeln ohne Android Studio installieren zu müssen.
