### ISSUE TITLE
Leaflet

### ISSUE THREAD

**Issue by LB31** [LB31/HikingForNerds#9]
- Leaflet API angucken
- Recherchieren, wie man die Daten offline visualisieren kann

**Comment by dephiloper** [comment]
### Standards
Es gibt eine Menge Standards zur Visualisierung von Kartendaten. Mit einer bestehenden Internetverbindung muss ein Tileserver angegeben werden welcher Tiles mit x und y Koordinaten und einer z Koordinate für den Zoom enthält (siehe [erster Test](https://wiki.openstreetmap.org/wiki/DE:OSM_mit_Leaflet/Vorbereitung)). Da Recherche für das Laden von offline Kartendaten durchgeführt werden sollten, wurde initial zu den beiden Standards **mbtiles (mapbox tiles)** und **pbf (protobuf)** recherchiert.
Das direkte Laden von diesen Formaten wird jedoch von leaflet nicht unterstützt, weshalb ein eigener Tileserver ggf. auf dem Mobilgerät ausgeführt werden muss. 

### Download von mbtiles/pbf
Die Dateien, die benötigt werden, um eine vektorbasierte Darstellung eines Kartenabschnitts darstellen zu können, werden im **[.mbtiles](https://github.com/mapbox/mbtiles-spec)** oder **.pbf** ausgeliefert und können von mehreren Seiten bezogen werden. Mbtiles können von der Welt oder einzelnen Kontinenten von der Seite [openandromaps.org](https://www.openandromaps.org/downloads/ubersichts-karten) bezogen werden. Bei diesen MBTiles handelt es sich um Raster-Tiles, die bereits in unterteilten Zoom-Stufen vorgeredet wurden. Vermutlich würde es auch die Möglichkeit geben, vektorbasierte MBTiles direkt zu rendern, um nicht an die vordefinierten Zoom-Stufen gebunden zu sein. Vektorbasierte MBTiles und besser unterteilte Kartenabschnitte sind auf der [openmaptiles-Seite](https://openmaptiles.org) verfügbar, wobei diese leider veraltet sind, außer man wäre gewillt, Geld zu bezahlen.
Aktuelle Karten in Form von pbf-Dateien können auf [geofabrik.de](http://download.geofabrik.de) erlangt werden.

### Plugins
Es existieren Plugins wie [Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid), welche prinzipiell das Laden von protobuf vector tiles unterstützen sollten. Damit wurden jedoch keine erfolgreichen Testergebnisse erzielt (aufgrund mangelhafter Dokumentation). Des Weiteren benötigt diese ebenfalls Tileserver, welche Tiles zu den zugehörigen Koordinaten bereitstellen.
Hierbei sollte weitere Recherche zum serverlosen Auslesen von map tiles durchgeführt werden.  

Zusätzlich gibt es Umsetzungen wie [leaflet.offline](https://github.com/allartk/leaflet.offline) und [leaflet-offline](https://github.com/robertomlsoares/leaflet-offline), diese verwenden aber den Browser um Kartendaten zu speichern. Dieses Verfahren könnte sich aber ggf. abgeschaut werden, um eigens eine Methode zur offline Speicherung von Kartendaten zu entwickeln.

Für das Anzeigen von MBTiles in LeafletJS gibt es das [MBTiles.js Plugin](https://unpkg.com/browse/Leaflet.TileLayer.MBTiles@1.0.0/). Dieses ermöglicht das Anzeigen von offline abgespeicherten .mbtiles-Dateien, die Raster-Tiles beinhalten. Es ist anzumerken, dass vektorbasierte Tiles zwar geladen, aber ohne separates Rendern nicht angezeigt werden können. Eine [Beispiel-Implementierung](https://stackoverflow.com/questions/43743097/showing-an-offline-osm-map-file-suggestion-an-mb-tiles-file-with-js-library) funktioniert bereits mit den MBTiles von **openandromaps.org**.

Zu untersuchen wäre des Weiteren das Darstellen von vektorbasierten MBTiles anhand von [Mapbox GL JS](https://github.com/klokantech/vector-tiles-sample). Dahingehend könnte das Rendern der Maptiles auch on-the-fly geschehen, ohne direkte Zoom-Stufen vorgeben zu müssen. Ein Problem könnte jedoch die Performance darstellen, da fraglich ist, ob das Rendern von Maptiles ebenfalls in einer akzeptablen Zeit auf einem mobilen Endgerät realisiert werden kann.

#### Tangram
Tangram ES soll wohl laut [diesem Blockbeitrag](http://theoutpost.io/modern-map-renderers/tangram-es/) ebenfalls das Lesen von offline Daten (mbtiles) ermöglichen. Dazu könnte ggf. weitere Recherche betrieben werden.

**Comment by dephiloper** [comment]
Abschließend wurde sich gegen eine Realisierung eines Kartendienstes mit Leaflet entschieden, da durch die gewollte Offlinenutzung andernfalls zu hohe Speicherkapazitäten für das Haltung der rasterisierten Tiles (png's) notwendig wäre.

\+ gerenderte vector tiles sehen deutlich schöner aus!
